name: user_repository
description: "Repo that handles users"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: '0.0.1'

environment:
  sdk: '>=3.5.0-236.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  rxdart: ^0.28.0
  firebase_core: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # email_validator: '^2.1.17'

flutter:
  uses-material-design: true